!                                                                                    
! leaf1 — OSPF area 0, wariant A (ECMP, maximum-paths 3)                             
!                                                                                    
log stdout                                                                           
!                                                                                    
interface eth1                                                                       
ip ospf network point-to-point                                                      
ip ospf cost 10                                                                     
ip ospf dead-interval minimal hello-multiplier 4                                    
!                                                                                    
interface eth2                                                                       
ip ospf network point-to-point                                                      
ip ospf cost 10                                                                     
ip ospf dead-interval minimal hello-multiplier 4                                    
!                                                                                    
interface eth3                                                                       
ip ospf network point-to-point                                                      
ip ospf cost 10                                                                     
ip ospf dead-interval minimal hello-multiplier 4                                    
!                                                                                    
router ospf                                                                          
ospf router-id 10.255.2.1                                                           
network 10.10.0.0/16 area 0                                                         
network 10.1.1.0/24 area 0                                                          
network 10.255.2.1/32 area 0                                                        
passive-interface lo                                                                
passive-interface br-hosts                                                          
maximum-paths 3                                                                     
!